const Discord = require("discord.js");
module.exports = (client, message, args) => { 
    var server = message.guild; 
    const embed = new Discord.RichEmbed()
    .setColor("RANDOM")
    .setTitle("Ayuda")
    .setDescription("Comandos disponibles:")
    .setThumbnail(server.iconURL)
    .setAuthor(server.name, server.iconURL)
    .addField("Prefix:","EK")
    .addField("8ball:", "juego de pregutas")
    .addField("beer:", "dar una cerveza a alguien")
    .addField("cafe:", "das un café a alguien")
    .addField("hit:" ," golpear a alguien")
    .addField("buscaminas:","jugar buscaminas")
    .addField("pat:", "acaricias a alguien")
    .addField("hug:", "abrazar a alguien")
    .addField("img:" ," busco una imagen en internet")
    .addField("love:" ," te doy amor <3")
    .addField("sleep:", "a dormir")
    .addField("shot:" ," le disparo a alguien")
    .addField("thirium:" ," te doy thirium")
    .addField("hamburger:", "dar una hamburguesa a alguien")
    .addField("mineserver:" ,"Miro el estatus de un server de Minecraft (Debes poner el IP del server)")
    .addField("ship:" ," shippeo a dos usuarios que menciones")
    .addField("ppt:" ," jugamos piedra papel o tijera")
    .addField("say:" ," Digo lo que tu digas (SOLO MODS)")
    .addField("sayembed:" ," Digo lo que tu digas (SOLO MODS)")
    message.channel.send(embed);    
    }